1. Generate two  3 x 3 matrix and find it's dot product and take the transpose of the answer.

In [1]:
#please provide your answer below this line.
import numpy as np
x = np.random.rand(3,3)
y = np.random.rand(3,3)
 
print(x)
print(y)
 
a=np.dot(x,y)
print(a)
a.transpose()

[[0.05951861 0.82209984 0.34256425]
 [0.32812262 0.03062988 0.50463608]
 [0.97840274 0.99371739 0.6700835 ]]
[[0.39370209 0.2552185  0.73921646]
 [0.56082973 0.04546029 0.44250865]
 [0.16124617 0.82933744 0.11862903]]
[[0.5397278  0.33666451 0.44842149]
 [0.22773135 0.503649   0.31597212]
 [1.05055386 0.85060649 1.2424713 ]]


array([[0.5397278 , 0.22773135, 1.05055386],
       [0.33666451, 0.503649  , 0.85060649],
       [0.44842149, 0.31597212, 1.2424713 ]])

2. Create a 3x3 matrix with elements [55,25,15], [30,44,2], [11,45,77] . Now find the determinant of the given matrix.

In [2]:
#please provide your answer below this line.
import numpy as np
a=[[55,25,15], [30,44,2], [11,45,77]]
b=np.array(a)
print(b)
np.linalg.det(b)

[[55 25 15]
 [30 44  2]
 [11 45 77]]


137180.0000000001