1. Generate a 3 x 3 matrix using random module.

In [1]:
#please provide your answer below this line.
import numpy as np
n = np.random.rand(3,3)
print(n)

[[0.76390595 0.15409237 0.74949136]
 [0.04289228 0.59114813 0.33580837]
 [0.15764397 0.62120396 0.65738562]]


2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [2]:
#please provide your answer below this line.
x=np.arange(2,18).reshape(4,4)
y=np.arange(6,22).reshape(4,4)
 
X=np.vstack(x).reshape(8,2)
 
Y=np.hstack(y).reshape(2,8)
 
print(X)
 
print(Y)

[[ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]]
[[ 6  7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20 21]]
